site_name: My Docs
theme:
  name: 'material'
  nav:
    - 河南: index.md
    - 使用手册:
        - Writing your docs: user-guide/writing-your-docs.md
        - Styling your docs: user-guide/styling-your-docs.md
    - 关于:
        - License: about/license.md
        - Release Notes: about/release-notes.md