site_name: My Docs
theme:
  name: 'material'
  palette:
    primary: cyan
nav:
#    - 数据结构学习:
#        - 线性表:
    - 河南:
        - smile: index.md
    - 博客:
        - Writing your docs: mystyle/1.index.md
        - Styling your docs: mystyle/2.index.md
    - 关于:
        - Release Notes: about/release-notes.md