site_name: My Docs
theme:
  name: 'material'
  palettr:
    primary: cyan
nav:
   - 河南: index.md
   - 博客:
       - Writing your docs:
       - Styling your docs:
   - 关于:
       - License: about/license.md
       - Release Notes: about/release-notes.md