site_name: My Docs
theme:
  name: 'material'
  palette:
    primary: yellow
nav:
    - 学习:
        - 01: index.md
    - 河南:
        - smile: Love/friends.md
    - 博客:
        - Writing your docs: style/1.index.md
        - Styling your docs: Love/Dictum.md
        - class notes:  style/就业指导.md
    - 关于:
        - Release Notes: about/release-notes.md